on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          ./update.sh
          git config user.name sirekanian
          git config user.email sirekanian@pm.me
          git add input list-of-war-enablers.json
          git commit -m updated || true
          git push
